/**
 * 知乎风格模拟数据
 * 为各个Tab提供统一格式的帖子数据
 */

// 模拟作者数据
const AUTHORS = [
  { id: 'user1', name: '张三', avatar: 'https://i.pravatar.cc/150?img=1', bio: '哥伦比亚大学 · CS专业' },
  { id: 'user2', name: '李四', avatar: 'https://i.pravatar.cc/150?img=5', bio: '留学顾问 · 5年经验' },
  { id: 'user3', name: '王五', avatar: 'https://i.pravatar.cc/150?img=8', bio: '东京大学 · 在读' },
  { id: 'user4', name: '赵六', avatar: 'https://i.pravatar.cc/150?img=12', bio: '纽约 · 产品经理' },
  { id: 'user5', name: '孙七', avatar: 'https://i.pravatar.cc/150?img=15', bio: '加州大学伯克利分校' },
  { id: 'user6', name: '周八', avatar: 'https://i.pravatar.cc/150?img=20', bio: 'UCL · 金融专业' },
  { id: 'user7', name: '吴九', avatar: 'https://i.pravatar.cc/150?img=25', bio: '签证顾问 · 资深' },
  { id: 'user8', name: '郑十', avatar: 'https://i.pravatar.cc/150?img=30', bio: '多伦多 · 软件工程师' },
];

// 留学Tab数据
export const STUDY_POSTS = {
  application: [
    {
      id: 'study_app_1',
      author: AUTHORS[0],
      title: '从GPA 3.0到哥大录取的完整逆袭之路',
      content: '我的背景是双非院校，GPA 3.2，托福105，GRE 325。申请季的时候完全是自己DIY，没有找中介。今天想分享一下我的申请经验，希望能帮到大家...',
      cover: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=400',
      coverPosition: 'bottom',
      tags: ['美国留学', 'DIY申请', 'CS专业'],
      stats: { likes: 1200, comments: 89, collects: 234, shares: 56, views: 8500 },
      time: '3天前',
      liked: false,
      collected: false,
    },
    {
      id: 'study_app_2',
      author: AUTHORS[5],
      title: '英国G5申请经验分享：从零到UCL offer',
      content: '分享我的英国G5申请经验，包括文书准备、面试技巧等...',
      cover: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=400',
      coverPosition: 'right',
      tags: ['英国留学', 'G5', '申请经验'],
      stats: { likes: 856, comments: 67, collects: 178, shares: 34, views: 5600 },
      time: '5天前',
      liked: false,
      collected: false,
    },
    {
      id: 'study_app_3',
      author: AUTHORS[1],
      title: '留学申请时间线规划：提前多久准备最合适？',
      content: '作为留学顾问，我经常被问到这个问题。今天就来详细说说...',
      cover: null,
      coverPosition: 'none',
      tags: ['申请规划', '时间线', '留学准备'],
      stats: { likes: 1456, comments: 123, collects: 345, shares: 45, views: 12000 },
      time: '1周前',
      liked: false,
      collected: false,
    },
  ],
  schools: [
    {
      id: 'study_school_1',
      author: AUTHORS[4],
      title: '美国Top 30大学申请难度全面对比',
      content: '结合近三年的录取数据，分析各校的申请难度和录取偏好...',
      cover: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=400',
      coverPosition: 'bottom',
      tags: ['美国大学', '申请难度', '院校对比'],
      stats: { likes: 2340, comments: 178, collects: 567, shares: 89, views: 15600 },
      time: '2天前',
      liked: false,
      collected: false,
    },
    {
      id: 'study_school_2',
      author: AUTHORS[5],
      title: 'UCL vs 爱丁堡：两所英国名校该怎么选？',
      content: '从专业排名、就业前景、生活成本等多个维度对比...',
      cover: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=400',
      coverPosition: 'right',
      tags: ['英国大学', '院校选择', 'UCL'],
      stats: { likes: 976, comments: 89, collects: 234, shares: 45, views: 6700 },
      time: '4天前',
      liked: false,
      collected: false,
    },
  ],
  exams: [
    {
      id: 'study_exam_1',
      author: AUTHORS[4],
      title: '托福115分备考经验分享：3个月从80到115',
      content: '从托福80到115，我用了3个月。今天分享一下我的备考方法和资料...',
      cover: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=400',
      coverPosition: 'bottom',
      tags: ['托福', '语言考试', '备考经验'],
      stats: { likes: 1567, comments: 123, collects: 456, shares: 67, views: 9800 },
      time: '3天前',
      liked: false,
      collected: false,
    },
    {
      id: 'study_exam_2',
      author: AUTHORS[0],
      title: 'GRE 335分经验：数学170+语文165是怎么做到的',
      content: '分享我的GRE备考心得，重点讲解Verbal如何突破160...',
      cover: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=400',
      coverPosition: 'right',
      tags: ['GRE', '备考攻略', '高分经验'],
      stats: { likes: 1234, comments: 98, collects: 345, shares: 56, views: 7800 },
      time: '5天前',
      liked: false,
      collected: false,
    },
  ],
  scholarship: [
    {
      id: 'study_scholar_1',
      author: AUTHORS[1],
      title: '美国大学奖学金申请全攻略：如何提高获奖概率',
      content: '详细介绍各类奖学金的申请条件、材料准备和申请技巧...',
      cover: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=400',
      coverPosition: 'bottom',
      tags: ['奖学金', '美国留学', '经济资助'],
      stats: { likes: 1876, comments: 145, collects: 567, shares: 78, views: 11000 },
      time: '2天前',
      liked: false,
      collected: false,
    },
    {
      id: 'study_scholar_2',
      author: AUTHORS[5],
      title: 'CSC公派留学申请经验：成功拿到全额资助',
      content: '分享CSC申请的全过程，包括材料准备、面试技巧等...',
      cover: null,
      coverPosition: 'none',
      tags: ['CSC', '公派留学', '全额奖学金'],
      stats: { likes: 2134, comments: 189, collects: 678, shares: 92, views: 13500 },
      time: '1周前',
      liked: false,
      collected: false,
    },
  ],
};

// 工作Tab数据
export const WORK_POSTS = {
  jobsearch: [
    {
      id: 'work_job_1',
      author: AUTHORS[3],
      title: '硅谷求职经验分享：从投简历到拿offer全流程',
      content: '在硅谷找工作的这半年，投了300+份简历，面试了50+家公司，最终拿到了5个offer...',
      cover: 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=400',
      coverPosition: 'bottom',
      tags: ['硅谷求职', 'Tech行业', '求职经验'],
      stats: { likes: 2456, comments: 189, collects: 678, shares: 92, views: 14800 },
      time: '2天前',
      liked: false,
      collected: false,
    },
    {
      id: 'work_job_2',
      author: AUTHORS[7],
      title: '加拿大IT就业市场分析：2025年最新趋势',
      content: '结合最新的就业数据，分析加拿大IT行业的就业形势...',
      cover: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400',
      coverPosition: 'right',
      tags: ['加拿大就业', 'IT行业', '就业分析'],
      stats: { likes: 1234, comments: 98, collects: 345, shares: 56, views: 7800 },
      time: '4天前',
      liked: false,
      collected: false,
    },
  ],
  interview: [
    {
      id: 'work_interview_1',
      author: AUTHORS[7],
      title: 'Google面试真题分享：L4 SWE面试全流程',
      content: '刚刚拿到Google的offer，分享一下我的面试经历和真题...',
      cover: 'https://images.unsplash.com/photo-1573164713988-8665fc963095?w=400',
      coverPosition: 'bottom',
      tags: ['Google面试', '技术面试', '面试真题'],
      stats: { likes: 3456, comments: 234, collects: 890, shares: 123, views: 18900 },
      time: '1天前',
      liked: true,
      collected: false,
    },
    {
      id: 'work_interview_2',
      author: AUTHORS[3],
      title: '行为面试（Behavioral Interview）终极攻略',
      content: '总结了最常见的50个行为面试问题和STAR回答法...',
      cover: null,
      coverPosition: 'none',
      tags: ['行为面试', '面试技巧', 'STAR方法'],
      stats: { likes: 1987, comments: 156, collects: 567, shares: 78, views: 12300 },
      time: '3天前',
      liked: false,
      collected: false,
    },
  ],
  companies: [
    {
      id: 'work_company_1',
      author: AUTHORS[3],
      title: 'FAANG公司对比：工资、文化、晋升全方位分析',
      content: '在FAANG工作过的朋友们，来分享一下各家公司的真实情况...',
      cover: 'https://images.unsplash.com/photo-1549924231-f129b911e442?w=400',
      coverPosition: 'right',
      tags: ['FAANG', '公司对比', '职场文化'],
      stats: { likes: 2876, comments: 198, collects: 745, shares: 98, views: 16700 },
      time: '5天前',
      liked: false,
      collected: false,
    },
  ],
  career: [
    {
      id: 'work_career_1',
      author: AUTHORS[7],
      title: '在美国做软件工程师3年：职业发展心得',
      content: '从Junior到Senior的成长之路，分享我的经验和教训...',
      cover: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400',
      coverPosition: 'bottom',
      tags: ['职业发展', '软件工程师', '成长经验'],
      stats: { likes: 1678, comments: 123, collects: 456, shares: 67, views: 10200 },
      time: '4天前',
      liked: false,
      collected: false,
    },
  ],
};

// 签证Tab数据
export const VISA_POSTS = {
  student: [
    {
      id: 'visa_student_1',
      author: AUTHORS[6],
      title: '美国F1签证面签攻略：100%通过的经验分享',
      content: '刚刚拿到F1签证，分享我的准备过程和面签经验...',
      cover: 'https://images.unsplash.com/photo-1569098644584-210bcd375b59?w=400',
      coverPosition: 'bottom',
      tags: ['F1签证', '美国签证', '面签攻略'],
      stats: { likes: 1876, comments: 145, collects: 567, shares: 78, views: 11000 },
      time: '2天前',
      liked: false,
      collected: false,
    },
    {
      id: 'visa_student_2',
      author: AUTHORS[6],
      title: '英国学生签证申请详解：2025年最新政策',
      content: '英国学生签证的申请流程、材料清单和注意事项...',
      cover: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=400',
      coverPosition: 'right',
      tags: ['英国签证', '学生签证', '签证政策'],
      stats: { likes: 1234, comments: 98, collects: 345, shares: 56, views: 7800 },
      time: '5天前',
      liked: false,
      collected: false,
    },
  ],
  work: [
    {
      id: 'visa_work_1',
      author: AUTHORS[2],
      title: 'H1B抽签政策最新解读（2025版）',
      content: '2025年H1B抽签有以下几个重大变化：1. 抽签时间提前到3月；2. 硕士及以上学历优先级提高...',
      cover: null,
      coverPosition: 'none',
      tags: ['H1B', '工作签证', '美国'],
      stats: { likes: 2340, comments: 156, collects: 567, shares: 89, views: 14500 },
      time: '1天前',
      liked: true,
      collected: false,
    },
  ],
  tourist: [
    {
      id: 'visa_tourist_1',
      author: AUTHORS[6],
      title: '美国B1/B2旅游签证申请全攻略',
      content: '详细介绍美国旅游签证的申请流程、材料准备和面签技巧...',
      cover: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=400',
      coverPosition: 'bottom',
      tags: ['旅游签证', '美国签证', 'B1/B2'],
      stats: { likes: 1456, comments: 112, collects: 389, shares: 56, views: 8900 },
      time: '3天前',
      liked: false,
      collected: false,
    },
  ],
  immigration: [
    {
      id: 'visa_immigration_1',
      author: AUTHORS[7],
      title: '加拿大EE移民全流程分享：从准备到获批',
      content: '分享我的加拿大EE移民经历，包括打分、材料准备、等待时间等...',
      cover: 'https://images.unsplash.com/photo-1503614472-8c93d56e92ce?w=400',
      coverPosition: 'bottom',
      tags: ['加拿大移民', 'EE移民', '移民经验'],
      stats: { likes: 2876, comments: 198, collects: 745, shares: 98, views: 16700 },
      time: '1周前',
      liked: false,
      collected: false,
    },
  ],
};

// 生活Tab数据
export const LIFE_POSTS = {
  housing: [
    {
      id: 'life_housing_1',
      author: AUTHORS[3],
      title: '纽约租房避坑指南：新手必看的10个注意事项',
      content: '在纽约租房3年的经验总结，帮你避开各种坑...',
      cover: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=400',
      coverPosition: 'bottom',
      tags: ['纽约租房', '租房攻略', '生活指南'],
      stats: { likes: 1567, comments: 123, collects: 456, shares: 67, views: 9800 },
      time: '2天前',
      liked: false,
      collected: false,
    },
    {
      id: 'life_housing_2',
      author: AUTHORS[5],
      title: '伦敦租房全攻略：从找房到签约',
      content: '详细介绍伦敦租房的各个环节和注意事项...',
      cover: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=400',
      coverPosition: 'right',
      tags: ['伦敦租房', '租房指南', '英国生活'],
      stats: { likes: 1234, comments: 98, collects: 345, shares: 56, views: 7800 },
      time: '5天前',
      liked: false,
      collected: false,
    },
  ],
  food: [
    {
      id: 'life_food_1',
      author: AUTHORS[3],
      title: '纽约必吃的10家中餐厅推荐',
      content: '作为在纽约生活3年的老司机，今天给大家推荐一些我常去的中餐厅...',
      cover: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=400',
      coverPosition: 'bottom',
      tags: ['纽约美食', '中餐推荐', '美食指南'],
      stats: { likes: 876, comments: 67, collects: 234, shares: 34, views: 5400 },
      time: '3天前',
      liked: false,
      collected: true,
    },
  ],
  transport: [
    {
      id: 'life_transport_1',
      author: AUTHORS[7],
      title: '多伦多公共交通完全指南：TTC使用攻略',
      content: '详细介绍多伦多TTC的使用方法、票价、常用线路等...',
      cover: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=400',
      coverPosition: 'right',
      tags: ['多伦多交通', 'TTC', '生活指南'],
      stats: { likes: 987, comments: 78, collects: 267, shares: 45, views: 6200 },
      time: '4天前',
      liked: false,
      collected: false,
    },
  ],
  finance: [
    {
      id: 'life_finance_1',
      author: AUTHORS[3],
      title: '留学生理财攻略：如何在美国开户和理财',
      content: '分享留学生在美国的银行开户、信用卡申请、理财投资等经验...',
      cover: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=400',
      coverPosition: 'bottom',
      tags: ['留学生理财', '银行开户', '信用卡'],
      stats: { likes: 1678, comments: 134, collects: 489, shares: 72, views: 10500 },
      time: '2天前',
      liked: false,
      collected: false,
    },
  ],
};

// 其他Tab数据
export const OTHER_POSTS = {
  knowledge: [
    {
      id: 'other_knowledge_1',
      author: AUTHORS[1],
      title: '留学小知识：GPA、CGPA、WES认证详解',
      content: '详细解释各种GPA计算方法和成绩认证的相关知识...',
      cover: null,
      coverPosition: 'none',
      tags: ['留学知识', 'GPA', '成绩认证'],
      stats: { likes: 1456, comments: 112, collects: 389, shares: 56, views: 8900 },
      time: '3天前',
      liked: false,
      collected: false,
    },
  ],
  policy: [
    {
      id: 'other_policy_1',
      author: AUTHORS[1],
      title: '2025年美国留学政策重大变化汇总',
      content: '盘点2025年美国留学的最新政策变化，包括签证、OPT等...',
      cover: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=400',
      coverPosition: 'bottom',
      tags: ['留学政策', '美国留学', '2025政策'],
      stats: { likes: 2345, comments: 178, collects: 678, shares: 92, views: 14200 },
      time: '1天前',
      liked: false,
      collected: false,
    },
  ],
  culture: [
    {
      id: 'other_culture_1',
      author: AUTHORS[2],
      title: '跨文化交流技巧：如何快速融入当地生活',
      content: '分享我在海外生活的文化适应经验和交流技巧...',
      cover: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400',
      coverPosition: 'right',
      tags: ['跨文化交流', '文化适应', '海外生活'],
      stats: { likes: 1234, comments: 98, collects: 345, shares: 56, views: 7800 },
      time: '5天前',
      liked: false,
      collected: false,
    },
  ],
  tools: [
    {
      id: 'other_tools_1',
      author: AUTHORS[4],
      title: '留学必备APP推荐：提高效率的20款神器',
      content: '推荐留学生必备的各类APP，包括学习、生活、社交等...',
      cover: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400',
      coverPosition: 'bottom',
      tags: ['实用工具', 'APP推荐', '效率工具'],
      stats: { likes: 1876, comments: 145, collects: 567, shares: 78, views: 11000 },
      time: '4天前',
      liked: false,
      collected: false,
    },
  ],
};

